[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'AWS IoT Export Service'
Timeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080
  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = './logs/aws-export.log'

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic=""

[ApplicationSettings]
AwsIoTMQTTHost      = "***.iot.us-west-2.amazonaws.com"
AwsIoTMQTTPort      = "8883"
awsIoTThingName     = "testThing"
MQTTCert            = "./certs/user.client.crt"
MQTTKey             = "./certs/user.client.key"
SkipCertVerify	    = "false"
PersistOnError	    = "false"
topic               = "$aws/things/testThing/shadow/update"
AwsDeviceNames      = ""
